controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

calculator:
    path: /calculator
    controller: App\Controller\CalculatorController::calculatorAction
